global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alert.rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['app:5000']
        
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
